(ns storj.node.pb-test
  "Cross-implementation vectors for the signed forms.

  Every hex string here was produced by `testdata/gen_vectors.go`, which links
  `storj.io/common` and asks Storj's own `signing.EncodeOrderLimit`,
  `EncodeOrder` and `EncodePieceHash` what they emit. Nothing in this file was
  derived by reading the .proto and reasoning — that method produced a first
  implementation which was wrong in two independent ways, and neither would
  have shown up as anything but signatures that refuse to verify:

  1. `limit`, `action` and `satellite_signature` were assigned field numbers
     8, 9 and 6. They are 6, 7 and 10.
  2. An unset timestamp was assumed to reach the wire as seconds = 0. It
     reaches the wire as seconds = -62135596800 — Go's zero time is year 1,
     not the epoch — and the signing form drops it on that basis."
  (:require [clojure.test :refer [deftest is testing]]
            [proto.wire :as w]
            [storj.node.pb :as pb]))

(defn- unhex [s]
  (mapv #?(:clj  #(Integer/parseInt % 16)
           :cljs #(js/parseInt % 16))
        (re-seq #"[0-9a-fA-F]{2}" s)))

(defn- hex [bs]
  (apply str (map (fn [b]
                    (let [v (bit-and (int b) 0xff)
                          s #?(:clj (Integer/toHexString v) :cljs (.toString v 16))]
                      (if (= 1 (count s)) (str "0" s) s)))
                  bs)))

;; ── vectors — generated by testdata/gen_vectors.go, do not hand-edit ─────────

(def order-limit-wire
  (str "0a100102030405060708090a0b0c0d0e0f10"
       "1220101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f"
       "2220404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f"
       "2a20707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f"
       "308080403801"
       "420b088092b8c398feffffff01"
       "4a0608c0b3a2d306"
       "5204deadbeef"
       "620608b097a2d306"
       "6a20a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf"))

(def order-limit-signing
  (str "0a100102030405060708090a0b0c0d0e0f10"
       "1220101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f"
       "2220404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f"
       "2a20707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f"
       "308080403801"
       "4a0608c0b3a2d306"
       "620608b097a2d306"
       "6a20a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf"))

;; The same limit carrying field 31, which this build's schema does not list.
;; Written out rather than derived from the two above so that CI's drift check
;; — which regenerates the vectors and looks for each one in this file — can
;; see them.
(def order-limit-unknown-wire
  (str "0a100102030405060708090a0b0c0d0e0f10"
       "1220101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f"
       "2220404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f"
       "2a20707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f"
       "308080403801"
       "420b088092b8c398feffffff01"
       "4a0608c0b3a2d306"
       "5204deadbeef"
       "620608b097a2d306"
       "6a20a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf"
       "f8012a"))

(def order-limit-unknown-signing
  (str "0a100102030405060708090a0b0c0d0e0f10"
       "1220101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f"
       "2220404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f"
       "2a20707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f"
       "308080403801"
       "4a0608c0b3a2d306"
       "620608b097a2d306"
       "6a20a0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf"
       "f8012a"))

(def order-wire    "0a100102030405060708090a0b0c0d0e0f10108080021a02cafe")
(def order-signing "0a100102030405060708090a0b0c0d0e0f1010808002")

;; piece_id (1), hash (2), signature (3), piece_size (4), timestamp (5).
;; hash_algorithm (6) is SHA256 = 0, which proto3 omits.
(def piece-hash-wire
  (str "0a20707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f"
       "1220b0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecf"
       "1a021122" "208020" "2a0608b097a2d306"))

(def piece-hash-signing
  (str "0a20707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f"
       "1220b0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecf"
       "208020" "2a0608b097a2d306"))

(def piece-hash-zero-ts-wire
  (str "0a20707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f"
       "1220b0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecf"
       "1a021122" "208020" "2a0b088092b8c398feffffff01"))

(def piece-hash-zero-ts-signing
  (str "0a20707172737475767778797a7b7c7d7e7f808182838485868788898a8b8c8d8e8f"
       "1220b0b1b2b3b4b5b6b7b8b9babbbcbdbebfc0c1c2c3c4c5c6c7c8c9cacbcccdcecf"
       "208020"))

;; ── the signed forms ─────────────────────────────────────────────────────────

(deftest order-limit-signing-bytes
  (testing "reproduces signing.EncodeOrderLimit"
    (is (= (unhex order-limit-signing)
           (pb/encode-order-limit-for-signing (w/decode (unhex order-limit-wire))))))

  (testing "the wire form is not the signed form"
    (is (not= (unhex order-limit-wire) (unhex order-limit-signing))
        "signing the received bytes as-is would verify nothing"))

  (testing "what changed between them"
    (let [wire   (w/decode (unhex order-limit-wire))
          signed (w/decode (unhex order-limit-signing))
          nums   #(set (map :field-number %))]
      (is (contains? (nums wire) 10) "wire carries the satellite signature")
      (is (not (contains? (nums signed) 10)) "the signed form does not")
      (is (contains? (nums wire) 8) "wire carries piece_expiration, unset though it is")
      (is (not (contains? (nums signed) 8)) "and the signed form drops it")
      (is (contains? (nums signed) 9) "order_expiration was set, so it stays")
      (is (contains? (nums signed) 12) "as does order_creation"))))

(deftest unknown-fields-are-signed-over
  ;; EncodeOrderLimit copies XXX_unrecognized across. A satellite on a newer
  ;; schema signs fields this build has never heard of; dropping them would
  ;; fail every signature it issues.
  (is (= (unhex order-limit-unknown-signing)
         (pb/encode-order-limit-for-signing (w/decode (unhex order-limit-unknown-wire)))))
  (is (= 12 (count (w/decode (unhex order-limit-unknown-wire))))
      "field 31 is present and unrecognised")
  (is (= [31] (->> (w/decode (unhex order-limit-unknown-signing))
                   (remove #(contains? pb/order-limit (:field-number %)))
                   (map :field-number)))
      "and survives into the signed bytes, last"))

(deftest order-signing-bytes
  (is (= (unhex order-signing)
         (pb/encode-order-for-signing (w/decode (unhex order-wire))))))

(deftest piece-hash-signing-bytes
  (testing "a set timestamp is kept"
    (is (= (unhex piece-hash-signing)
           (pb/encode-piece-hash-for-signing (w/decode (unhex piece-hash-wire))))))
  (testing "a zero timestamp is dropped, exactly as EncodePieceHash drops it"
    (is (= (unhex piece-hash-zero-ts-signing)
           (pb/encode-piece-hash-for-signing (w/decode (unhex piece-hash-zero-ts-wire)))))))

;; ── reading fields ───────────────────────────────────────────────────────────

(deftest reads-the-fields-a-node-acts-on
  (let [limit (w/decode (unhex order-limit-wire))]
    (is (= 1048576 (pb/get-varint limit pb/order-limit :limit)))
    (is (= :put (pb/get-enum limit pb/order-limit :action pb/piece-action)))
    (is (= 32 (count (pb/get-bytes limit pb/order-limit :satellite-id))))
    (is (= 32 (count (pb/get-bytes limit pb/order-limit :storage-node-id))))
    (is (= 16 (count (pb/get-bytes limit pb/order-limit :serial-number))))
    (is (= [0xde 0xad 0xbe 0xef]
           (pb/get-bytes limit pb/order-limit :satellite-signature)))))

(deftest timestamps
  (let [limit (w/decode (unhex order-limit-wire))]
    (testing "an unset timestamp reads as nil, not as the epoch"
      (is (nil? (pb/timestamp-seconds
                 (pb/get-field limit pb/order-limit :piece-expiration)))))
    (testing "a set one reads as seconds"
      ;; 2026-07-28T12:00:00Z
      (is (= 1785240000 (pb/timestamp-seconds
                         (pb/get-field limit pb/order-limit :order-expiration))))
      ;; 2026-07-28T11:00:00Z
      (is (= 1785236400 (pb/timestamp-seconds
                         (pb/get-field limit pb/order-limit :order-creation)))))))

(deftest unknown-enum-values-are-not-nil
  ;; A node that reads an action it does not know as "no action" would treat a
  ;; future PieceAction as a malformed limit rather than as one it must refuse.
  (let [limit (-> (w/decode (unhex order-limit-wire))
                  (w/remove-field 7)
                  (conj (w/varint-field 7 99)))]
    (is (= [:unknown 99] (pb/get-enum limit pb/order-limit :action pb/piece-action)))))

(deftest round-trip-through-the-codec-is-lossless
  (doseq [[name h] [["order limit" order-limit-wire]
                    ["order limit with an unknown field" order-limit-unknown-wire]
                    ["order" order-wire]
                    ["piece hash" piece-hash-wire]]]
    (testing name
      (is (= (unhex h) (w/encode (w/decode (unhex h))))))))

(deftest hex-helper-agrees-with-itself
  ;; guards the test's own plumbing, which the vectors depend on
  (is (= order-wire (hex (unhex order-wire)))))
