// Command gen_checkin emits the bytes storj.io/common marshals for a
// CheckInRequest, and the bytes of a CheckInResponse to read back.
//
// The request is the interesting one. `storj.node.contact` builds it field by
// field from the .proto, and reasoning from a .proto is precisely how one
// writes a message that encodes cleanly and means something else — the
// deprecated free_bandwidth at field 1 of NodeCapacity is one trap, and gogo's
// treatment of the nullable=false timestamp inside NodeVersion is another.
//
//	cd testdata && go run gen_checkin.go > checkin-vectors.edn
package main

import (
	"encoding/hex"
	"fmt"

	"storj.io/common/pb"
)

func main() {
	req := &pb.CheckInRequest{
		Address: "127.0.0.1:28967",
		Version: &pb.NodeVersion{
			Version: "1.104.5",
			Release: true,
		},
		Capacity: &pb.NodeCapacity{
			FreeDisk: 1 << 40,
		},
		Operator: &pb.NodeOperator{
			Email:  "op@example.com",
			Wallet: "0xabc",
		},
	}
	reqBytes, err := pb.Marshal(req)
	if err != nil {
		panic(err)
	}

	// A refusal, because that is the response worth being able to read: the
	// call succeeded and the node is not on the network.
	refused := &pb.CheckInResponse{
		PingNodeSuccess:  false,
		PingErrorMessage: "failed to dial storage node (ID: 1abc) at address 127.0.0.1:28967",
	}
	refusedBytes, err := pb.Marshal(refused)
	if err != nil {
		panic(err)
	}

	accepted := &pb.CheckInResponse{
		PingNodeSuccess:     true,
		PingNodeSuccessQuic: true,
		NodeTagSuccess:      true,
	}
	acceptedBytes, err := pb.Marshal(accepted)
	if err != nil {
		panic(err)
	}

	fmt.Println("{;; generated by testdata/gen_checkin.go — do not hand-edit")
	fmt.Printf(" :%-24s %q\n", "check-in-request", hex.EncodeToString(reqBytes))
	fmt.Printf(" :%-24s %q\n", "response-refused", hex.EncodeToString(refusedBytes))
	fmt.Printf(" :%-24s %q\n", "response-accepted", hex.EncodeToString(acceptedBytes))
	fmt.Printf(" :%-24s %q\n", "ping-error-message", refused.PingErrorMessage)
	fmt.Println("}")
}
