// Command gen_vectors emits reference vectors for storj.node.* by running
// Storj's own implementation.
//
// This is not part of the library and nothing in src/ depends on it. It exists
// because the interesting parts of this protocol cannot be checked against
// themselves. Whether `encode-order-limit-for-signing` produces the bytes a
// satellite actually signed is a question about gogoproto's treatment of
// nullable=false fields and Go's definition of a zero time — reasoning about
// it from the .proto is exactly how one ends up with a plausible
// implementation that verifies nothing.
//
// So the expected values in test/storj/node/pb_test.cljc are produced here,
// by linking storj.io/common and asking it. Regenerate with:
//
//	cd testdata && go run gen_vectors.go
//
// and diff the output against the literals in the test.
package main

import (
	"context"
	"encoding/hex"
	"fmt"
	"time"

	"storj.io/common/pb"
	"storj.io/common/signing"
	"storj.io/common/storj"
)

func bytes32(fill byte) []byte {
	b := make([]byte, 32)
	for i := range b {
		b[i] = fill + byte(i)
	}
	return b
}

func main() {
	ctx := context.Background()

	var satelliteID, storageNodeID storj.NodeID
	copy(satelliteID[:], bytes32(0x10))
	copy(storageNodeID[:], bytes32(0x40))

	var pieceID storj.PieceID
	copy(pieceID[:], bytes32(0x70))

	var serial storj.SerialNumber
	copy(serial[:], bytes32(0x01)[:16])

	var uplinkKey storj.PiecePublicKey
	// a PiecePublicKey wraps an ed25519 key; only its serialized bytes matter here
	uplinkKey, _ = storj.PiecePublicKeyFromBytes(bytes32(0xa0))

	orderExpiration := time.Date(2026, 7, 28, 12, 0, 0, 0, time.UTC)
	orderCreation := time.Date(2026, 7, 28, 11, 0, 0, 0, time.UTC)

	limit := &pb.OrderLimit{
		SerialNumber:  serial,
		SatelliteId:   satelliteID,
		StorageNodeId: storageNodeID,
		PieceId:       pieceID,
		Limit:         1 << 20,
		Action:        pb.PieceAction_PUT,
		// PieceExpiration deliberately left as the Go zero time: this is the
		// case the signing form drops and the wire form still emits.
		OrderExpiration:     orderExpiration,
		OrderCreation:       orderCreation,
		UplinkPublicKey:     uplinkKey,
		SatelliteSignature:  []byte{0xde, 0xad, 0xbe, 0xef},
	}

	emit := func(name string, b []byte, err error) {
		if err != nil {
			panic(err)
		}
		fmt.Printf(" :%-28s %q\n", name, hex.EncodeToString(b))
	}

	fmt.Println("{;; generated by testdata/gen_vectors.go — do not hand-edit")

	wire, err := pb.Marshal(limit)
	emit("order-limit-wire", wire, err)
	sig, err := signing.EncodeOrderLimit(ctx, limit)
	emit("order-limit-signing", sig, err)

	// the same limit carrying a field this build does not know about.
	// EncodeOrderLimit copies XXX_unrecognized across, so it must survive.
	unknown := &pb.OrderLimit{}
	*unknown = *limit
	unknown.XXX_unrecognized = []byte{0xf8, 0x01, 0x2a} // field 31, varint 42
	wireU, err := pb.Marshal(unknown)
	emit("order-limit-unknown-wire", wireU, err)
	sigU, err := signing.EncodeOrderLimit(ctx, unknown)
	emit("order-limit-unknown-signing", sigU, err)

	order := &pb.Order{
		SerialNumber:    serial,
		Amount:          1 << 15,
		UplinkSignature: []byte{0xca, 0xfe},
	}
	wireO, err := pb.Marshal(order)
	emit("order-wire", wireO, err)
	sigO, err := signing.EncodeOrder(ctx, order)
	emit("order-signing", sigO, err)

	hash := &pb.PieceHash{
		PieceId:       pieceID,
		Hash:          bytes32(0xb0),
		PieceSize:     4096,
		Timestamp:     orderCreation,
		Signature:     []byte{0x11, 0x22},
		HashAlgorithm: pb.PieceHashAlgorithm_SHA256,
	}
	wireH, err := pb.Marshal(hash)
	emit("piece-hash-wire", wireH, err)
	sigH, err := signing.EncodePieceHash(ctx, hash)
	emit("piece-hash-signing", sigH, err)

	// a piece hash whose timestamp is the Go zero value — dropped for signing
	hashZ := &pb.PieceHash{}
	*hashZ = *hash
	hashZ.Timestamp = time.Time{}
	wireHZ, err := pb.Marshal(hashZ)
	emit("piece-hash-zero-ts-wire", wireHZ, err)
	sigHZ, err := signing.EncodePieceHash(ctx, hashZ)
	emit("piece-hash-zero-ts-signing", sigHZ, err)

	fmt.Printf(" :%-28s %q\n", "satellite-id-hex", hex.EncodeToString(satelliteID[:]))
	fmt.Printf(" :%-28s %q\n", "piece-id-hex", hex.EncodeToString(pieceID[:]))
	fmt.Printf(" :%-28s %q\n", "satellite-id-b58", satelliteID.String())
	fmt.Printf(" :%-28s %q\n", "piece-id-b32", pieceID.String())
	fmt.Println("}")
}
