// Command gen_piecestore emits a real upload conversation: the messages an
// uplink sends to store one piece, built with storj.io/common's own types.
//
// One message type carries four different things and nothing in the encoding
// says which is which, so a state machine reading these has to be driven by
// real ones. Reasoning from the .proto produces a reader that accepts a limit
// in the middle of a stream and calls it valid.
//
//	cd testdata && go run gen_piecestore.go > piecestore-vectors.edn
package main

import (
	"context"
	"encoding/hex"
	"fmt"
	"time"

	proto "github.com/gogo/protobuf/proto"

	"storj.io/common/pb"
	"storj.io/common/pkcrypto"
	"storj.io/common/signing"
	"storj.io/common/storj"
)

func fill(start byte, n int) []byte {
	b := make([]byte, n)
	for i := range b {
		b[i] = start + byte(i)
	}
	return b
}

func main() {
	ctx := context.Background()

	key, err := pkcrypto.GeneratePrivateKey()
	if err != nil {
		panic(err)
	}
	pub, err := pkcrypto.PublicKeyFromPrivate(key)
	if err != nil {
		panic(err)
	}
	spki, err := pkcrypto.PublicKeyToPKIX(pub)
	if err != nil {
		panic(err)
	}

	var satID, nodeID storj.NodeID
	copy(satID[:], fill(0x10, 32))
	copy(nodeID[:], fill(0x40, 32))
	var pieceID storj.PieceID
	copy(pieceID[:], fill(0x70, 32))

	piecePub, piecePriv, err := storj.NewPieceKey()
	if err != nil {
		panic(err)
	}

	limit, err := signing.SignOrderLimit(ctx,
		&signing.PrivateKey{Self: satID, Key: key},
		&pb.OrderLimit{
			SerialNumber:    storj.SerialNumber{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16},
			SatelliteId:     satID,
			StorageNodeId:   nodeID,
			PieceId:         pieceID,
			Limit:           64,
			Action:          pb.PieceAction_PUT,
			OrderExpiration: time.Date(2026, 8, 1, 0, 0, 0, 0, time.UTC),
			UplinkPublicKey: piecePub,
		})
	if err != nil {
		panic(err)
	}

	// the conversation: limit, then two chunks, then done
	first := &pb.PieceUploadRequest{Limit: limit}

	data := fill(0xa0, 40)
	chunk1 := &pb.PieceUploadRequest{
		Chunk: &pb.PieceUploadRequest_Chunk{Offset: 0, Data: data[:16]},
	}
	chunk2 := &pb.PieceUploadRequest{
		Chunk: &pb.PieceUploadRequest_Chunk{Offset: 16, Data: data[16:]},
	}

	hash, err := signing.SignUplinkPieceHash(ctx, piecePriv, &pb.PieceHash{
		PieceId:   pieceID,
		Hash:      fill(0x01, 32),
		PieceSize: int64(len(data)),
		Timestamp: time.Date(2026, 7, 30, 0, 0, 0, 0, time.UTC),
	})
	if err != nil {
		panic(err)
	}
	done := &pb.PieceUploadRequest{Done: hash}

	// A download needs its own limit: the action is part of what the satellite
	// signed, so a PUT limit cannot authorise a GET. The upload's limit is
	// emitted against a download request too, because "a PUT limit cannot
	// serve a download" is a rule worth having a vector for.
	getLimit, err := signing.SignOrderLimit(ctx,
		&signing.PrivateKey{Self: satID, Key: key},
		&pb.OrderLimit{
			SerialNumber:    storj.SerialNumber{2, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16},
			SatelliteId:     satID,
			StorageNodeId:   nodeID,
			PieceId:         pieceID,
			Limit:           64,
			Action:          pb.PieceAction_GET,
			OrderExpiration: time.Date(2026, 8, 1, 0, 0, 0, 0, time.UTC),
			UplinkPublicKey: piecePub,
		})
	if err != nil {
		panic(err)
	}
	dl := &pb.PieceDownloadRequest{
		Limit: getLimit,
		Chunk: &pb.PieceDownloadRequest_Chunk{Offset: 8, ChunkSize: 16},
	}
	dlWrongAction := &pb.PieceDownloadRequest{
		Limit: limit,
		Chunk: &pb.PieceDownloadRequest_Chunk{Offset: 8, ChunkSize: 16},
	}
	dlTooBig := &pb.PieceDownloadRequest{
		Limit: getLimit,
		Chunk: &pb.PieceDownloadRequest_Chunk{Offset: 0, ChunkSize: 65},
	}

	enc := func(m proto.Message) string {
		b, err := pb.Marshal(m)
		if err != nil {
			panic(err)
		}
		return hex.EncodeToString(b)
	}

	fmt.Println("{;; generated by testdata/gen_piecestore.go — do not hand-edit")
	fmt.Printf(" :%-22s %q\n", "satellite-spki", hex.EncodeToString(spki))
	fmt.Printf(" :%-22s %q\n", "storage-node-id", hex.EncodeToString(nodeID[:]))
	fmt.Printf(" :%-22s %q\n", "piece-id", hex.EncodeToString(pieceID[:]))
	fmt.Printf(" :%-22s %d\n", "order-limit-bytes", 64)
	fmt.Printf(" :%-22s %d\n", "expiration-unix",
		time.Date(2026, 8, 1, 0, 0, 0, 0, time.UTC).Unix())
	fmt.Printf(" :%-22s %q\n", "upload-first", enc(first))
	fmt.Printf(" :%-22s %q\n", "upload-chunk-1", enc(chunk1))
	fmt.Printf(" :%-22s %q\n", "upload-chunk-2", enc(chunk2))
	fmt.Printf(" :%-22s %q\n", "upload-done", enc(done))
	fmt.Printf(" :%-22s %q\n", "data", hex.EncodeToString(data))
	fmt.Printf(" :%-22s %q\n", "download-first", enc(dl))
	fmt.Printf(" :%-22s %q\n", "download-wrong-action", enc(dlWrongAction))
	fmt.Printf(" :%-22s %q\n", "download-too-big", enc(dlTooBig))
	fmt.Println("}")
}
