// Command gen_bloom emits a bloom filter built by storj.io/common's own
// implementation, together with its answers for a set of piece ids.
//
// The answers are the point. A filter that decodes is not a filter that agrees:
// every probe reads a little-endian uint64 out of the piece id and takes it
// modulo the table size, and a number that large does not survive a JavaScript
// double. Two implementations disagreeing about which bucket a piece lands in
// disagree about which pieces to delete.
//
//	cd testdata && go run gen_bloom.go > bloom-vectors.edn
package main

import (
	"encoding/hex"
	"fmt"

	"storj.io/common/bloomfilter"
	"storj.io/common/storj"
)

func pieceID(fill byte) storj.PieceID {
	var id storj.PieceID
	for i := range id {
		id[i] = fill + byte(i*7)
	}
	return id
}

func main() {
	// An explicit seed, so this is reproducible. 200 puts the seed past 32 and
	// past 64, which is what selects a rangeOffset other than the first —
	// initialConditions divides by 32 and indexes rangeOffsets, and an
	// implementation that hardcodes offset 9 passes every test with seed 0.
	const seed, hashCount, sizeInBytes = 200, 4, 137
	filter := bloomfilter.NewExplicit(seed, hashCount, sizeInBytes)

	members := []byte{0x00, 0x11, 0x40, 0x99, 0xf0}
	for _, m := range members {
		filter.Add(pieceID(m))
	}

	fmt.Println("{;; generated by testdata/gen_bloom.go — do not hand-edit")
	fmt.Printf(" :%-18s %d\n", "seed", seed)
	fmt.Printf(" :%-18s %d\n", "hash-count", hashCount)
	fmt.Printf(" :%-18s %d\n", "size-in-bytes", sizeInBytes)
	fmt.Printf(" :%-18s %q\n", "filter", hex.EncodeToString(filter.Bytes()))
	fmt.Printf(" :%-18s %.6f\n", "fill-rate", filter.FillRate())

	// Every answer, members and non-members alike. The non-members matter more:
	// a false positive costs disk and a false negative costs a customer's data.
	fmt.Print(" :answers [")
	for fill := 0; fill < 256; fill += 8 {
		id := pieceID(byte(fill))
		fmt.Printf("\n  {:piece-id %q :contains %t}",
			hex.EncodeToString(id[:]), filter.Contains(id))
	}
	fmt.Println("]")

	// and a seed of zero, which is the one an implementation that ignores
	// initialConditions happens to get right
	zero := bloomfilter.NewExplicit(0, 3, 64)
	zero.Add(pieceID(0x11))
	fmt.Printf(" :%-18s %q\n", "zero-seed-filter", hex.EncodeToString(zero.Bytes()))
	fmt.Printf(" :%-18s %t\n", "zero-seed-contains-11", zero.Contains(pieceID(0x11)))
	fmt.Printf(" :%-18s %t\n", "zero-seed-contains-22", zero.Contains(pieceID(0x22)))
	fmt.Println("}")
}
