// Command gen_identity produces a real Storj identity and records it, then —
// in -verify mode — reads the recording back and asserts Storj's own code
// still agrees with it.
//
// Identity generation is random, so unlike gen_vectors.go this cannot be
// regenerated byte for byte. The fixture is therefore checked in and the CI
// job runs -verify instead of a diff: it parses the recorded DER with
// storj.io/common and asserts the node ID, version and chain relationships are
// what the EDN claims. That is a stronger check than regeneration anyway —
// it holds the fixture to the reference implementation rather than to a
// previous run of this program.
//
//	cd testdata && go run gen_identity.go            # write identity.edn
//	cd testdata && go run gen_identity.go -verify    # check it
package main

import (
	"context"
	"crypto/x509"
	"encoding/hex"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strings"

	"storj.io/common/identity"
	"storj.io/common/peertls"
	"storj.io/common/storj"
)

const path = "identity.edn"

func main() {
	verify := flag.Bool("verify", false, "verify the recorded identity instead of generating one")
	flag.Parse()

	if *verify {
		doVerify()
		return
	}
	doGenerate()
}

func doGenerate() {
	// Difficulty 8 is the smallest the network's own accounting can report,
	// because Difficulty() credits a whole byte for the version byte it skips.
	// A real storage node needs 36, which is minutes of hashing and would make
	// this fixture expensive to regenerate for no extra coverage: the shape of
	// the certificate is identical either way.
	ca, err := identity.NewCA(context.Background(), identity.NewCAOptions{
		Difficulty:  8,
		Concurrency: 1,
	})
	if err != nil {
		panic(err)
	}
	ident, err := ca.NewIdentity()
	if err != nil {
		panic(err)
	}

	spki, err := x509.MarshalPKIXPublicKey(ca.Cert.PublicKey)
	if err != nil {
		panic(err)
	}
	difficulty, err := ident.ID.Difficulty()
	if err != nil {
		panic(err)
	}

	var b strings.Builder
	b.WriteString("{;; generated by testdata/gen_identity.go — regenerating gives a\n")
	b.WriteString(" ;; different identity, which is why CI runs -verify instead of a diff\n")
	fmt.Fprintf(&b, " :%-22s %q\n", "ca-der", hex.EncodeToString(ca.Cert.Raw))
	fmt.Fprintf(&b, " :%-22s %q\n", "leaf-der", hex.EncodeToString(ident.Leaf.Raw))
	fmt.Fprintf(&b, " :%-22s %q\n", "ca-spki-der", hex.EncodeToString(spki))
	fmt.Fprintf(&b, " :%-22s %q\n", "ca-tbs", hex.EncodeToString(ca.Cert.RawTBSCertificate))
	fmt.Fprintf(&b, " :%-22s %q\n", "ca-signature", hex.EncodeToString(ca.Cert.Signature))
	fmt.Fprintf(&b, " :%-22s %q\n", "leaf-tbs", hex.EncodeToString(ident.Leaf.RawTBSCertificate))
	fmt.Fprintf(&b, " :%-22s %q\n", "leaf-signature", hex.EncodeToString(ident.Leaf.Signature))
	fmt.Fprintf(&b, " :%-22s %q\n", "node-id", ident.ID.String())
	fmt.Fprintf(&b, " :%-22s %q\n", "node-id-hex", hex.EncodeToString(ident.ID.Bytes()))
	fmt.Fprintf(&b, " :%-22s %d\n", "difficulty", difficulty)
	fmt.Fprintf(&b, " :%-22s %d\n", "version", ident.ID.Version().Number)
	fmt.Fprintf(&b, " :%-22s %q\n", "sig-alg", ca.Cert.SignatureAlgorithm.String())
	for _, ext := range ca.Cert.Extensions {
		fmt.Fprintf(&b, " :%-22s %q\n",
			"ca-ext-"+strings.ReplaceAll(ext.Id.String(), ".", "-"),
			hex.EncodeToString(ext.Value))
	}
	b.WriteString("}\n")

	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Print(b.String())
}

func field(src, name string) string {
	m := regexp.MustCompile(`:` + name + `\s+"([^"]*)"`).FindStringSubmatch(src)
	if m == nil {
		panic("missing field: " + name)
	}
	return m[1]
}

func unhex(s string) []byte {
	b, err := hex.DecodeString(s)
	if err != nil {
		panic(err)
	}
	return b
}

func check(what string, ok bool) {
	if !ok {
		fmt.Printf("FAIL %s\n", what)
		os.Exit(1)
	}
	fmt.Printf("ok   %s\n", what)
}

func doVerify() {
	raw, err := os.ReadFile(path)
	if err != nil {
		panic(err)
	}
	src := string(raw)

	caCert, err := x509.ParseCertificate(unhex(field(src, "ca-der")))
	if err != nil {
		panic(err)
	}
	leafCert, err := x509.ParseCertificate(unhex(field(src, "leaf-der")))
	if err != nil {
		panic(err)
	}

	id, err := identity.NodeIDFromCert(caCert)
	if err != nil {
		panic(err)
	}
	check("node id derives from the recorded CA cert", id.String() == field(src, "node-id"))
	check("node id hex matches", hex.EncodeToString(id.Bytes()) == field(src, "node-id-hex"))

	spki, err := x509.MarshalPKIXPublicKey(caCert.PublicKey)
	if err != nil {
		panic(err)
	}
	check("recorded SPKI is the CA's", hex.EncodeToString(spki) == field(src, "ca-spki-der"))
	check("recorded tbs is the CA's",
		hex.EncodeToString(caCert.RawTBSCertificate) == field(src, "ca-tbs"))
	check("recorded leaf tbs is the leaf's",
		hex.EncodeToString(leafCert.RawTBSCertificate) == field(src, "leaf-tbs"))

	// the chain relationships this library's admission rules depend on
	check("the CA is self-signed",
		caCert.CheckSignature(caCert.SignatureAlgorithm,
			caCert.RawTBSCertificate, caCert.Signature) == nil)
	check("the leaf is signed by the CA",
		caCert.CheckSignature(leafCert.SignatureAlgorithm,
			leafCert.RawTBSCertificate, leafCert.Signature) == nil)
	check("chain verification passes",
		peertls.VerifyPeerCertChains(nil, [][]*x509.Certificate{{leafCert, caCert}}) == nil)

	v, err := storj.IDVersionFromCert(caCert)
	if err != nil {
		panic(err)
	}
	check("version matches", fmt.Sprint(v.Number) == field2(src, "version"))
}

func field2(src, name string) string {
	m := regexp.MustCompile(`:` + name + `\s+(\d+)`).FindStringSubmatch(src)
	if m == nil {
		panic("missing numeric field: " + name)
	}
	return m[1]
}
